<?php include 'header.php'; ?>
        <div id="cont_left">
            <h2 style="text-align: right; line-height: 0; text-align: left;"><a href="year1c.php"><strong><- Page 3</strong></a></h2>
			<p><a href="images/suc_img/lousepeopleJPG_s8strg37gx.jpg"><img class="right" src="images/suc_img/lousepeopleJPG_s8strg37gx.jpg" /></a>Now there are louse-people about! I see two louse-women and a louse-man. This is truly things I have never seen before, hopefully they leave us alone.</p><div class="clear"></div>
			<p><a href="images/suc_img/migrantsJPG_6wx0k3brt9.jpg"><img class="left" src="images/suc_img/migrantsJPG_6wx0k3brt9.jpg" /></a>Some migrants arrived, no doubt they heard of CrestedGilt throughout the lands, and they wanted to join us! That brings us up to 13 dwarfs now. With these migrant was an fisherman and a great fish cleaner! time to make a fishery near the main hall, by the still.</p>
			<p><a href="images/suc_img/farmplotandfamrerJPG_p5562mx5r9.jpg"><img class="right" src="images/suc_img/farmplotandfamrerJPG_p5562mx5r9.jpg" /></a>Like I said before, we embarked with the normal supply of goods, good strong ale and food to last us a while but we need to STRIKE THE EARTH and dig deep and create underground farming and start to plant these plump helmet spawn we brought with us. I was noticing the other dwarfs eyeing them with saliva in their mouths for consumption as we made the journey here but I stopped them! I'm glad I did, or else we wouldn't have anything to plant. I don't even know the farmer dwarfs name but he plants a mean plump helmet spawn.</p>
        </div><!--cont_left-->
        <div id="cont_right">
            <p><a href="images/suc_img/dormJPG_gx1sie7qr7.jpg"><img class="right" src="images/suc_img/dormJPG_gx1sie7qr7.jpg" /></a>As the farm is coming along nicely I turn my attention to digging deeper into the mountain, we need a small dorm to get these other dwarfs out of the elements and away from any nasty creatures that may lurk outside. So I began to dig out spaces for that as well, while the woodcutter dwarfs makes a carpenter's workshop and begins construction of some beds for use to use. I personally can sleep anywhere but some of these limp-wrist dwarfs want a bed to be happy. Whatever, a happy dwarf does its job so I cannot complain too much of this issue. Maybe later I'll make a room for each of them but I have bigger fish to fry.</p>
			<p><a href="images/suc_img/fishzoneandsteelheadtroutJPG_w87q0v1w7a.jpg"><img class="right" src="images/suc_img/fishzoneandsteelheadtroutJPG_w87q0v1w7a.jpg" /></a>Like real fish! Some of the new migrants know how to fish so I set up a small fishing zone on the river right in front of our cave, I don't want them wandering the area trying out all the lakes, and look at the giant fish he caught one!</p>
			<h2 style="padding: 0; margin: 0; text-align: right; line-height: 0;"><a href="year1e.php"><strong>Page 5 -></strong></a></h2>
        </div><!--cont_right-->
<?php include 'footer.php'; ?>