<?php include 'header.php'; ?>
        <div id="cont_left">
			<h2 style="text-align: right; line-height: 0; text-align: left;"><a href="year2f.php"><strong><- Page 6</strong></a></h2>
			<p><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">O</span>n the 25th of Obsidian, the entry is brief: a kidnapper has taken baby Mebzuth in the commotion. This is all that is written on this day, so this historian believes that the ambush is still going strong but wonders if Mebzuth is the baby first spoken about in this record. If that is the case, this historian believes it might, indeed, be Overload's child.</p>
			<p><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">O</span>n the 27th of Obsidian Overload updates about the army; the goblins have taken out the Military Commander and the entire force is down to eight people. This historian wonders about the baby's fate and if it is Overload's offspring (and how he can be so callous if that is, indeed, his child.) This historian also wishes to know the fate of the second dead Kol.</p>
			<p><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">O</span>n the 28th, Overload begins to point fingers at everyone but himself for this goblin catastrophe. He says "idiot dorfs are trying to go outside to get shit from the dead army but goblins are still there" - if you are the ruler, why not rule? Keep the doors barred, I want to scream - don't let them go to slaughter!</p>
			<p><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">O</span>n the 1st of Granite, year 253, this faded document ends. Overload writes that the goblin army is still going strong and his "militia" (now no longer an army of Kols in his eyes) has been reduced to three souls. He also writes that the Kols have only managed to bruise the wrist of one of the goblins over the course of the past week, which is astounding given the fact they downed similar beasts only weeks earlier. </p>
        </div><!--cont_left-->
        <div id="cont_right">
			<p>Overload also writes that babies have started to go missing and the forgotten beast broke down the stone door and is currently beginning the climb up into the fortress. On this day, it had made it all the way to level 50 and was rapidly approaching the living quarters. Again, Overload notes Gylis (perhaps they were friends) and here states Gylis is just "presumed" dead. This historian supposed that Overload never sent anyone to confirm his death - perhaps he just ceased hearing the poor man's screams from behind the door?</p>
            <p><div class="thumb-right"><a href="images/suc_img/year2_7.png"><img src="images/suc_img/year2_7.png" /></a>Overload, in his quarters, penning his final entry.</div><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">T</span>he last words on the record are simple, and show the true cowardice of this man Overload: I RETIRE.</p>
			<p><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">W</span>e will continue excavation in hopes we can find another document detailing the survival (or downfall) of this fortress. This historian hopes that this chronicle is not the last and that a new, more competent dwarf stepped in after Overload slithered away like the toad this record clearly paints him to be. This fortress is vast, and deep - such a great people deserve more than this. I hope they live on.</p>
			<h1 align="center" style="font-family: 'Glass Antiqua', cursive; font-size: 38px;">The End of Year 2</h1>
			<h1 align="center" style="font-family: 'Glass Antiqua', cursive; font-size: 38px; margin: 30px 0 0 0;"><a href="year2aa.php"><strong>Year 2 Addendum -></strong></a></h1>
        </div><!--cont_right-->
<?php include 'footer.php'; ?>