<?php include 'header.php'; ?>
        <div id="cont_left">
			<h2 style="text-align: right; line-height: 0; text-align: left;"><a href="year2e.php"><strong><- Page 5</strong></a></h2>
			<p>The fragments include the term "the military turns out to not be shitty" which makes this historian conclude that Overload never trained his men (or watched their drills if they had them) but they are armed to some degree.</p>
			<p><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">O</span>n the 25th of Timber, the fragments look up for once - Overload has secured "lots of wood" from the merchants. He does state this only will help for the short term, but it is something. This historian is sad that human lives were traded for wood when plenty of trees stand all around this ruin.</p>
			<p>In the month of Moonstone, only one entry is made - on the 9th day there is still wood, and it is helping the fortress, but Overload is aware that the solution is temporary and digging continues to find alternative fuel.</p>
			<p><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">O</span>n the 9th of Obsidian, the fragments pick up with another report of a dwarf acting strangely. This entry uplifts this historian as Overload writes "I will not ignore it this time! No more insanity on my watch!" The man is learning! He might make a great leader yet. He writes that the crazed dwarf demands silk.</p>
			<p><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">O</span>n the 21st of Obsidian, Overload writes that silk thread is needed to make silk cloth for the crazed dwarf - it is clear that the breadth of industry within the fortress is lacking. At this point, the entry veers off course as Overload states that the dwarf who is suffering from madness must make an artifact to commemorate the first year of Overload's rule.</p>
        </div><!--cont_left-->
        <div id="cont_right">
			<p>While ruling for a year is a great milestone, why would you push a dwarf so clearly close to the edge when others have killed in such a state? Why is the dwarf not in a cage? Luckily, Overload sends Gylis (who we assume is a skilled dwarf, as we have never heard of him before in this record) to the underground caves to collect spider silk.</p>
			<p align="center"><a href="images/suc_img/year2_5.png"><img width="100%" src="images/suc_img/year2_5.png" /></a></p>
            <p><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">O</span>n the 22nd of Obsidian, darkness descends over the fortress. The words are bleak, so this historian will quote them directly: "oh shit a forgotten beast was in the cave and is fucking Gylis up. Mighty stone door is locked behind him." While this historian commends Overload for protecting his people, she shudders at the thought of sacrificing a man to a beast without even attempting a rescue, particularly since there is a standing army that is clearly capable of killing beasts.</p>
			<p><div class="thumb-right"><a href="images/suc_img/year2_6.png"><img src="images/suc_img/year2_6.png" /></a>Goblins!!</div><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">G</span>ylis is killed by the forgotten beast on the 23rd of Obsidian. Overload does not pause in his entry for this man whatsoever, but his reason may be valid. On the same day, goblins ambush the fortress. There may be no time for mourning.</p>
			<h2 style="padding: 0; margin: 0; text-align: right; line-height: 0;"><a href="year2g.php"><strong>Page 7 -></strong></a></h2>
        </div><!--cont_right-->
<?php include 'footer.php'; ?>