<?php include 'header.php'; ?>
        <div id="cont_left">
			<h2 style="text-align: right; line-height: 0; text-align: left;"><a href="year2a.php"><strong><- Page 1</strong></a></h2>
			<p><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">O</span>n the 7th of Felsite, Overload speaks of a dwarf and names him/her (gender unknown based on the records we have uncovered) - this is the first record we have discovered of a named dwarf besides the author himself. This dwarf, called Dee-Em VII, has been partying for days and Overload blames the stagnation of his metalsmithing endeavor on these festivities. In his notes, he notes that he must "plan a smear campaign for Dee-Em VII" - while no records indicate that there were official holidays around early Felsite, this historian wonders why an extended revelry would cause such anger.</p>
			<p><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">T</span>he 18th of Felsite lends legitimacy to Overload's anger. It appears that Dee-Em VII's party is still going strong, and eleven days of any festival (big or small) would undoubtedly disrupt a fortress of this size. Overload notes that industry growth is suffering due to the party, but this historian wishes he had written more about what was going on with industry instead of focusing on the party. With the fragments recovered, we are unable to determine the size of the festival and how exactly it is causing issues with productivity. Based on Overload's early hubris, this historian is skeptical, but trying to remain impartial we note the frustrations of a new ruler and understand that subjects who blatantly disobey are troublesome indeed.</p>
        </div><!--cont_left-->
        <div id="cont_right">
			<p><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">A</span>n entry on the 20th of Felsite only notes that an elven caravan arriving - all worries about parties and industry have completely been forgotten. One wonders how Overload dealt with these issues (or if they were dealt with.)</p>
            <p><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">T</span>he 25th of Felsite is the longest entry to date - it appears that when Overload is most annoyed, he is the most descriptive. Today, the fortress had to trade all crafts and toys for cloth to appease "whiny farmers who claim seeds must be stored in bags." Overload muses that he must "figure out how to make food from stone and fire the farmers." While this commentary is humorous, the ire in his writings (and his earlier anger towards fisherman, who only wanted safety from wild animals) shows clearly that Overload values craft work and seemingly precious materials far more than the staples that keep his fortress alive: food.</p>
			<p><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">E</span>ntries again begin on the 9th of Hematite in early Summer when he encounters a dwarf in a "strange mood" demanding "body parts." This historian wonders if indeed farming operations were halted in late spring and this dwarf is showing early signs of starvation. Luckily, Overload does not punish the dwarf but instead orders the construction of a butcher's workshop and thinks about creating a tanner. We assume from this that although fishing operations are closed, dwarves do still leave the fortress to find meat above ground.</p>
			<h2 style="padding: 0; margin: 0; text-align: right; line-height: 0;"><a href="year2c.php"><strong>Page 3 -></strong></a></h2>
        </div><!--cont_right-->
<?php include 'footer.php'; ?>