<?php include 'header.php'; ?>
        <div id="cont_left">
            <h1 style="text-align: center;">Year 2</h1>
			<h2 style="text-align: center;">Ruler: <a href="http://chattyprofil.es/p/OverloadUT">OverloadUT</a></h2>
            <h3 style="text-align: center;">Archaeologist Journal of Dahan Ese, Lead Excavator</h3>
			<p><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">W</span>hilst excavating the remains of one of the largest Dwarven fortress we've found to date in the northwest quadrant, I came upon the scrawled remains of what looks to be one of the rulers of the fortress - albeit a short-lived reign, as the document fragments appear to only span for a year.</p>
			<p><div class="thumb-right"><a href="images/suc_img/year2_1.png"><img src="images/suc_img/year2_1.png" /></a>Every dwarf in the fortress helped smooth the stone of Overload's study.</div><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">O</span>n the 27th day of Granite, early Spring 252, a migrant named Overload came with a wave of thirty-one souls to the fortress. He made quick work of getting into the fortress and immediately found his clay housing deplorable, so within the season had named himself manager of the fortress and ordered the dwarves under his rule to build him a massive study. Our excavation seems to be concluding that the remains of this journal were discovered within the rubble of Overload's study.</p>
			<p><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">O</span>n the 17th of Slate, mid Spring of the same year, Overload noted that the first baby boy was born under his rule. Why he chose to note this as his first entry into the chronicle remains puzzling - perhaps it was Overloa's child (legitimate or not) and thus an achievement in his life.</p>
        </div><!--cont_left-->
        <div id="cont_right">
			<p>He does not write about the mother and in his first entry never mentioned if he came alone in the migrant wave, so we are left to conjecture here.</p>
            <p><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">O</span>n the 27th of Slate, wolverines encroached on the fisherman's wharf, causing the workers there to complain for safety's sake. Overload ruled that all fishing should be halted, proclaiming that "if it can't be done underground, it shouldn't be done" - this historian pauses a moment to note Overload's hubris and shortsightedness in this proclamation. Dwarves belong below the earth, but we also need to eat.</p>
			<p><div class="thumb-right"><a href="images/suc_img/year2_2.png"><img src="images/suc_img/year2_2.png" /></a>The Metalsmithing Hub.</div><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">T</span>he fragments are torn, but the next notation happens on the 3rd of Felsite, in late spring. Overload appears to be building now and has ordered construction of a metalsmithing hub. He plans to burn wood, get fuel, smelt metal, and make weapons. He also makes a quick note on the 5th of Felsite that the room designations are "shitty" and orders it "fixed" - he notes here that this is "boring" - this historian again pauses to marvel at the man's hubris and wonder why he took the time to note such a menial task when he, himself, pens that the task is boring. He is undertaking grand construction, yet trifling in room banality - and writing about it. This seems puzzling.</p>
			<h2 style="padding: 0; margin: 0; text-align: right; line-height: 0;"><a href="year2b.php"><strong>Page 2 -></strong></a></h2>
        </div><!--cont_right-->
<?php include 'footer.php'; ?>