<?php include 'header.php'; ?>
        <div id="cont_left">
			<h2 style="text-align: right; line-height: 0; text-align: left;"><a href="year2b.php"><strong><- Page 2</strong></a></h2>
			<p><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">O</span>n the 13th of Hematite Overload notes with alarm that he was too late and the dwarf who four days previous was acting strangely had gone insane. This historian wonders whether the fortress had an infirmary or jail - anything to keep dwarves who were acting out of the ordinary under quarantine - and why the raving dwarf was not at the very least put under observation. Due to this oversight, the crazed dwarf murdered two babies and a peon before being subdued and killed. The notes do not go into detail and say whether or not the crazed dwarf attempted to eat any of his victims. We are thankful for that.</p>
			<p><div class="thumb-right"><a href="images/suc_img/year2_3.png"><img src="images/suc_img/year2_3.png" /></a>The main level of the fortress.</div><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">E</span>ntries halt until the 12th of Malachite when Overload proclaims that "MEAT TASTES GOOD!" At first, this historian assumed that the entries stopped because Overload was busy dealing with security protocols following the murder (or in mourning) and we are both repulsed and yet strangely not surprised that instead he was focused on meat. He is painting a very selfish portrait of himself, but this entry must mean that the butcher shop was completed. Unfortunately, Overload says that "ALL LIVESTOCK MUST BE SLAUGHTERED" - we hope he speaks hyperbolically, but this historian is not certain that Overload knows the meaning of moderation.</p>
        </div><!--cont_left-->
        <div id="cont_right">
			<p><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">T</span>he 15th of Malachite focuses on the arrival of ten more migrants, one of who claims he is a fantastic chef. Overload immediately fires his old chef and hires this new, untested (and unknown) migrant to "make meat even more delicious." This historian feels that a fortress of this size should vet its newcomers more thoroughly - but Overload was able to take over the entire place within days of his arrival, so perhaps this is not surprising - although, those who gain power quickly can lose it just as quickly. One would think he would be more paranoid.</p>
            <p><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">E</span>ntries begin what we assume to be a full month later (currently, we have historians carefully mapping out the date patterns of this fortress) and is written on the 15th of Galena. Overload decides he needs an army (and then finds out "they already had one" - who killed the crazed dwarf if not the army? Did the citizens of the fortress have to take up arms on their own? How can one rule an entire fortress for months without finding out about the basic security of the grounds? What kind of society is Overload ruling over - and if they are as lawless as it sounds from this entry, how dangerous is the world? Could this society possibly have been so peaceful as to never need the mobilization or presence of an army?) Alas, Overload does not ponder the questions that this historian puzzles over - he fires the old army and hires a new one.</p>
			<h2 style="padding: 0; margin: 0; text-align: right; line-height: 0;"><a href="year2d.php"><strong>Page 4 -></strong></a></h2>
        </div><!--cont_right-->
<?php include 'footer.php'; ?>