<?php include 'header.php'; ?>
        <div id="cont_left">
			<h2 style="text-align: right; line-height: 0; text-align: left;"><a href="year2d.php"><strong><- Page 4</strong></a></h2>
			<p><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">T</span>he 13th of Sandstone brings twelve more migrants, but nothing notable is written about them.</p>
			<p><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">O</span>n the 20th of Sandstone, Overload again notes that the fortress still lacks wood. This historian is scanning the horizon and while our researchers are still not sure exactly how the year 252 in this Dwarven timeline relates to our own modern calendar, she sees a thick wood surrounding her and wonders if Overload refused to let dwarves out of the fortress for anything but hunting. Surely, hunters and lumberjacks should both be sent? In addition to the wood shortage, the fortress now has no iron and Overload's writing is bold and his desperation is clear: they need alternative fuel, immediately.</p>
			<p><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">N</span>o entries are logged until the 10th of Timber, and Overload's writing is still dire. The dwarves have dug to layer 100 (a mighty feat indeed) but no fuel has been found - they must continue digging. All Overload is focused on now is fuel.</p>
			<p><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">T</span>he 20th of Timber marks the arrival of a new caravan, but Overload does not even document how many came - just that he hopes they have fuel. This historian wonders why, if the fortress was in such dire straits, he did not leave his giant study to check on the fuel supplies instead of writing?</p>
        </div><!--cont_left-->
        <div id="cont_right">
			<p><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">O</span>n the 22nd of Timber, Overload writes that his army now has leather armor. This historian wonders if they have weapons and is appalled that they were not properly clothed until months after their conscription. I am also appalled by the fact that Overload says this armor is thanks to his own "taste for meat" - would he not have properly outfitted his army had he not had extra hide? This does suggest that a tanner was set up along with a butcher, though.</p>
            <p><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">T</span>he 24th of Timber shows a new side to both Overload and the fortress: the fragments talk about how Overload orders peons to bring captives inside cages to the merchant caravan to trade. This historian pauses to wonder when these cages were built (surely they should have been used to stop murders?) and what kind of vile fortress deals in the slave trade. Unfortunately, Overload does not delve deeper into this trade to shed light on whether it is ordinary and has been happening throughout his reign or something new because the entry, in frantic writing, states "OH GOD THEY LET THE GOBLINS AND WOLVERINES OUT OF THE CAGES INSTEAD OF BRINGING THEM WITH THE CAGE." Why in god's name are goblins and wolverines in cages? Why would captives be forced to share cages with these dangerous beasts? This historian seriously believes that Overload might be a simpleton, because the lack of basic logic is astounding. Fortunately, Overload notes that his military killed the wolverines and goblins and does not note any casualties from within the fortress. </p>
			<h2 style="padding: 0; margin: 0; text-align: right; line-height: 0;"><a href="year2f.php"><strong>Page 6 -></strong></a></h2>
        </div><!--cont_right-->
<?php include 'footer.php'; ?>