<?php include 'header.php'; ?>
        <div id="cont_left">
			<h2 style="text-align: right; line-height: 0; text-align: left;"><a href="year2c.php"><strong><- Page 3</strong></a></h2>
			<p>His army was built on the basis of men named "Kol" - Overload found that three men were all called that and so enlisted them as that seemed "as good a qualification as anything else". He then proceeded to rename seven more of his citizens to create an army of ten. This historian wonders if these citizens were jobless or at all trained in the skills of a solider. This historian also wonders if Overload is descending into full-fledged madness or if these wild acts are all due to his huge ego and deadly hubris.</p>
			<p><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">O</span>n the 22nd of Galena, the note is simple and dire - "OUT OF WOOD! NO MORE FUEL!" The log never notes what industry is running in the fortress and what (if any) it is producing. Could this fuel be solely to cook meat?</p>
			<p><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">O</span>n the 16th of Limestone (perhaps as much time has passed as a full month by this Dwarven calendar) Overload notes that there has been no more wood brought to the fortress. Only on this day he decides to search for alternative sources of fuel. This historian knows that Overload came as a migrant, and the record does not speak of his background or knowledge, but it is unbelievable how unable he is to run even the most basic parts of a fortress. He seems to lack all common sense and have no skills except, perhaps, writing. This historian wonders whether he is a conman of sorts - how else could he have usurped rule without an army or an uprising?</p>
        </div><!--cont_left-->
        <div id="cont_right">
			<p><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">O</span>n the 26th of Limestone, another citizen falls prey to madness. This time it is the butcher, who allegedly wanted bones. Overload notes "luckily he is just depressed and not killing anyone" leaving this historian to wonder if Overload does not know how to use his army or if the army is, in fact, useless beyond being all named "Kol." This historian also strongly believes that the only industry in this fortress is butchery given that metalsmithing has never been mentioned since Overload began construction (and never noted that he finished it.)</p>
            <p><div class="thumb-right"><a href="images/suc_img/year2_4.png"><img src="images/suc_img/year2_4.png" /></a>First discovered natural cave.</div><span style="font-family: 'Glass Antiqua', cursive; font-size: 48px;">O</span>n the 5th of Sandstone Overload finally turns his attentions back to the work happening within the fortress. Miners have been digging deep for fuel and found their first natural cave. A "mighty stone door" is constructed to protect the fortress from whatever may or may not lurk within the cave. This historian feels that Overload might finally be learning from his time ruling, although his note that "surely nothing could bash down a stone door" is ominous and his comments that "stone is mighty. The dwarves are mighty" leads this historian to believe that he again is leading the fortress to destruction because of his inflated self-worth and delusions of grandeur. After all, I am sitting amongst this mighty stone rubble and the bones of these mighty dwarves.</p>
			<h2 style="padding: 0; margin: 0; text-align: right; line-height: 0;"><a href="year2e.php"><strong>Page 5 -></strong></a></h2>
        </div><!--cont_right-->
<?php include 'footer.php'; ?>